# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import integration

class Ui_Form(object):
    def SubmitAction(self):
        integration.main()
        integration.set_data(self.Temperature.text(),self.Humidity.text(),self.WindSpeed.text(),self.SRFileNo.text(),self.AluminiumTemp.text(),self.ChemicalTemp.text(),self.LauricAcid.text(),self.StearicAcid.text(),
        self.ParafinWax.text(),self.LauricAcidComp.text(),self.StearicAcidWaxComp.text(),self.ParafinWaxComp.text())
        with open("Variables.txt", 'w') as file:
            file.write(self.Temperature.text() +" °C" + "\n")
            file.write(self.Humidity.text() +" %" + "\n")
            file.write(self.WindSpeed.text() +" km/hr" + "\n")
            file.write(self.SRFileNo.text() + "\n")
            file.write(self.AluminiumTemp.text() +" °C" + "\n")
            file.write(self.ChemicalTemp.text() +" °C" + "\n")
            file.write(self.LauricAcid.text() + "\n")
            file.write(self.StearicAcid.text() + "\n")
            file.write(self.ParafinWax.text() + "\n")
            file.write(self.LauricAcidComp.text() + "\n")
            file.write(self.StearicAcidWaxComp.text() + "\n")
            file.write(self.ParafinWaxComp.text() + "\n")
        file.close()

    def setupUi(self, Form):
        Form.setWindowTitle("Test Model")
        Form.setFixedSize(690, 389)
        Form.setObjectName("Form")
        Form.resize(690, 389)
        Form.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.SubmitButton = QtWidgets.QPushButton(Form)
        self.SubmitButton.setGeometry(QtCore.QRect(520, 350, 141, 31))
        self.SubmitButton.setStyleSheet("QPushButton {\n"
                                        "color: #000;\n"
                                        "border: 2px solid #555;\n"
                                        "border-radius: 20px;\n"
                                        "border-style: outset;\n"
                                        "background: qradialgradient(\n"
                                        "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                        "radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
                                        ");\n"
                                        "padding: 1px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "background: qradialgradient(\n"
                                        "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                        "radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
                                        ");\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "border-style: inset;\n"
                                        "background: qradialgradient(\n"
                                        "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                        "radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                        ");\n"
                                        "}")
        self.SubmitButton.setObjectName("SubmitButton")
        self.SubmitButton.clicked.connect(self.SubmitAction)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(340, 139, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 19, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(340, 259, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(340, 19, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.WindSpeed = QtWidgets.QSpinBox(Form)
        self.WindSpeed.setGeometry(QtCore.QRect(120, 129, 61, 31))
        self.WindSpeed.setStyleSheet("QSpinBox\n"
                                     "{\n"
                                     "border : 2px solid black;\n"
                                     "background : lightgrey;\n"
                                     "}\n"
                                     "\n"
                                     "")
        self.WindSpeed.setMaximum(99)
        self.WindSpeed.setObjectName("WindSpeed")
        self.LauricAcidComp = QtWidgets.QSpinBox(Form)
        self.LauricAcidComp.setGeometry(QtCore.QRect(560, 189, 71, 31))
        self.LauricAcidComp.setStyleSheet("QSpinBox\n"
                                          "{\n"
                                          "border : 2px solid black;\n"
                                          "background : lightgrey;\n"
                                          "}\n"
                                          "")
        self.LauricAcidComp.setObjectName("LauricAcidComp")
        self.LauricAcid = QtWidgets.QSpinBox(Form)
        self.LauricAcid.setGeometry(QtCore.QRect(460, 9, 71, 31))
        self.LauricAcid.setStyleSheet("QSpinBox\n"
                                      "{\n"
                                      "border : 2px solid black;\n"
                                      "background : lightgrey;\n"
                                      "}\n"
                                      "")
        self.LauricAcid.setObjectName("LauricAcid")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 319, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ParafinWaxComp = QtWidgets.QSpinBox(Form)
        self.ParafinWaxComp.setGeometry(QtCore.QRect(570, 310, 71, 31))
        self.ParafinWaxComp.setStyleSheet("QSpinBox\n"
                                          "{\n"
                                          "border : 2px solid black;\n"
                                          "background : lightgrey;\n"
                                          "}\n"
                                          "")
        self.ParafinWaxComp.setObjectName("ParafinWaxComp")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(340, 79, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Humidity = QtWidgets.QDoubleSpinBox(Form)
        self.Humidity.setGeometry(QtCore.QRect(110, 79, 71, 31))
        self.Humidity.setStyleSheet("QDoubleSpinBox\n"
                                    "{\n"
                                    "border : 2px solid black;\n"
                                    "background : lightgrey;\n"
                                    "}\n"
                                    "\n"
                                    "")
        self.Humidity.setObjectName("Humidity")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 139, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(340, 319, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.StearicAcidWaxComp = QtWidgets.QSpinBox(Form)
        self.StearicAcidWaxComp.setGeometry(QtCore.QRect(610, 249, 71, 31))
        self.StearicAcidWaxComp.setStyleSheet("QSpinBox\n"
                                              "{\n"
                                              "border : 2px solid black;\n"
                                              "background : lightgrey;\n"
                                              "}\n"
                                              "")
        self.StearicAcidWaxComp.setObjectName("StearicAcidWaxComp")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 199, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ChemicalTemp = QtWidgets.QDoubleSpinBox(Form)
        self.ChemicalTemp.setGeometry(QtCore.QRect(220, 309, 71, 31))
        self.ChemicalTemp.setStyleSheet("QDoubleSpinBox\n"
                                        "{\n"
                                        "border : 2px solid black;\n"
                                        "background : lightgrey;\n"
                                        "}\n"
                                        "\n"
                                        "")
        self.ChemicalTemp.setObjectName("ChemicalTemp")
        self.Temperature = QtWidgets.QDoubleSpinBox(Form)
        self.Temperature.setGeometry(QtCore.QRect(140, 19, 71, 31))
        self.Temperature.setStyleSheet("QDoubleSpinBox\n"
                                       "{\n"
                                       "border : 2px solid black;\n"
                                       "background : lightgrey;\n"
                                       "}\n"
                                       "\n"
                                       "")
        self.Temperature.setObjectName("Temperature")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 79, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 259, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ParafinWax = QtWidgets.QSpinBox(Form)
        self.ParafinWax.setGeometry(QtCore.QRect(470, 129, 71, 31))
        self.ParafinWax.setStyleSheet("QSpinBox\n"
                                      "{\n"
                                      "border : 2px solid black;\n"
                                      "background : lightgrey;\n"
                                      "}\n"
                                      "")
        self.ParafinWax.setObjectName("ParafinWax")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(340, 199, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.AluminiumTemp = QtWidgets.QDoubleSpinBox(Form)
        self.AluminiumTemp.setGeometry(QtCore.QRect(230, 249, 71, 31))
        self.AluminiumTemp.setStyleSheet("QDoubleSpinBox\n"
                                         "{\n"
                                         "border : 2px solid black;\n"
                                         "background : lightgrey;\n"
                                         "}\n"
                                         "\n"
                                         "")
        self.AluminiumTemp.setObjectName("AluminiumTemp")
        self.StearicAcid = QtWidgets.QSpinBox(Form)
        self.StearicAcid.setGeometry(QtCore.QRect(460, 69, 71, 31))
        self.StearicAcid.setStyleSheet("QSpinBox\n"
                                       "{\n"
                                       "border : 2px solid black;\n"
                                       "background : lightgrey;\n"
                                       "}\n"
                                       "")
        self.StearicAcid.setObjectName("StearicAcid")
        self.SRFileNo = QtWidgets.QSpinBox(Form)
        self.SRFileNo.setGeometry(QtCore.QRect(160, 189, 71, 31))
        self.SRFileNo.setStyleSheet("QSpinBox\n"
                                    "{\n"
                                    "border : 2px solid black;\n"
                                    "background : lightgrey;\n"
                                    "}\n"
                                    "")
        self.SRFileNo.setObjectName("SRFileNo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.SubmitButton.setText(_translate("Form", "Submit"))
        self.label_10.setText(_translate("Form", "Parafin Wax :"))
        self.label_2.setText(_translate("Form", "Temperature :"))
        self.label_12.setText(_translate("Form", "Stearic Acid Wax Composition :"))
        self.label_8.setText(_translate("Form", "Lauric Acid :"))
        self.label_7.setText(_translate("Form", "Chemical Temperature :"))
        self.label_9.setText(_translate("Form", "Stearic Acid :"))
        self.label_4.setText(_translate("Form", "Windspeed :"))
        self.label_13.setText(_translate("Form", "Parafin Wax Composition :"))
        self.label_5.setText(_translate("Form", "SR File Number :"))
        self.label_3.setText(_translate("Form", "Humidity :"))
        self.label_6.setText(_translate("Form", "Aluminium Temperature :"))
        self.label_11.setText(_translate("Form", "Lauric Acid Composition :"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
