# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject
from PyQt5.QtWidgets import QFileDialog


def Load():
    filename = QFileDialog.getOpenFileName(None, "Open Model",
                                           "", "Trained Model (*);")
    path = filename[0]
    print(path)
    if not os.stat("Path.txt").st_size == 0:
        file = open('Path.txt', 'w')
        file.write(path)
        file.close()


class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 10, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.ModelLabel = QtWidgets.QLabel(self.centralwidget)
        self.ModelLabel.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.ModelLabel.setObjectName("ModelLabel")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 50, 51, 41))
        self.pushButton_2.setStyleSheet("image: url(LoadIcon.png);border :1px solid black;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.LoadModelLabel = QtWidgets.QLabel(self.centralwidget)
        self.LoadModelLabel.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.LoadModelLabel.setObjectName("LoadModelLabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "color: #000;\n"
                                      "border: 2px solid #555;\n"
                                      "border-radius: 20px;\n"
                                      "border-style: outset;\n"
                                      "background: qradialgradient(\n"
                                      "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                      "radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
                                      ");\n"
                                      "padding: 1px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "background: qradialgradient(\n"
                                      "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                      "radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
                                      ");\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "border-style: inset;\n"
                                      "background: qradialgradient(\n"
                                      "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                      "radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                      ");\n"
                                      "}")
        self.LoadModelVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Load Model"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Pre installed model"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Load model"))
        self.ModelLabel.setText(_translate("MainWindow", "Model: "))
        self.LoadModelLabel.setText(_translate("MainWindow", "Load model:"))
        self.pushButton.setText(_translate("MainWindow", "Close"))

    def LoadModelVisible(self, visible):
        self.LoadModelLabel.setVisible(visible)
        self.pushButton_2.setVisible(visible)


class MyWindow(QtWidgets.QMainWindow, Ui_MainWindow):  # ++++
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(239, 138)
        self.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.activated.connect(self.updateMainWindow)
        self.pushButton_2.clicked.connect(Load)
        self.pushButton.clicked.connect(self.close)

    def updateMainWindow(self):
        if self.comboBox.currentIndex() == 0:
            self.LoadModelVisible(False)
        else:
            self.LoadModelVisible(True)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MyWindow()
    MainWindow.show()
    sys.exit(app.exec_())
