# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrainingPageDataErrorPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject

import CSS


class Ui_MainWindow(QObject):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(233, 83)

        self.ErrorMessage = QtWidgets.QLabel(Form)
        self.ErrorMessage.setGeometry(QtCore.QRect(10, 20, 211, 16))
        self.ErrorMessage.setObjectName("ErrorMessage")

        self.CloseButton = QtWidgets.QPushButton(Form)
        self.CloseButton.setGeometry(QtCore.QRect(150, 50, 75, 23))
        self.CloseButton.setObjectName("CloseButton")
        self.CloseButton.setStyleSheet(CSS.QPushButtonCSS)
        self.CloseButton.clicked.connect(self.close)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ErrorMessage.setText(_translate("Form", "Please import the dataset and images folder!"))
        self.CloseButton.setText(_translate("Form", "Close"))


class MyWindow(QtWidgets.QMainWindow, Ui_MainWindow):  # ++++
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setStyleSheet(CSS.BackgroundCSS)
