# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrainingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtNetwork
from PyQt5.QtCore import QObject, QThread
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QFileDialog
from train_neural_network import main as train

class MainBackgroundThread(QThread):
    def __init__(self, ImportDataPath, ImportImagesPath, Epoch,TrainingMode, TrainingRatio, LearningRate,Momentum,preview_image):
        QThread.__init__(self)
        self.ImportDataPath, self.ImportImagesPath,self.Epoch,self.TrainingMode, self.TrainingRatio, self.LearningRate,self.Momentum,self.PreviewImage = ImportDataPath, ImportImagesPath,Epoch,TrainingMode,TrainingRatio,LearningRate,Momentum,preview_image
    def run(self):
        train(self.ImportDataPath, self.ImportImagesPath,self.Epoch,self.TrainingMode,self.TrainingRatio,self.LearningRate,self.Momentum,self.PreviewImage)
class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        self.setWindowIcon(QIcon('TrainingIcon.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(600, 350)
        MainWindow.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.EpochText = QtWidgets.QLabel(self.centralwidget)
        self.EpochText.setGeometry(QtCore.QRect(230, 180, 47, 13))
        self.EpochText.setObjectName("EpochText")
        self.TrainModeText = QtWidgets.QLabel(self.centralwidget)
        self.TrainModeText.setGeometry(QtCore.QRect(230, 210, 81, 16))
        self.TrainModeText.setObjectName("TrainModeText")
        self.TrainingRatioText = QtWidgets.QLabel(self.centralwidget)
        self.TrainingRatioText.setGeometry(QtCore.QRect(230, 250, 71, 16))
        self.TrainingRatioText.setObjectName("TrainingRatioText")
        self.Epoch = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Epoch.setGeometry(QtCore.QRect(290, 180, 62, 22))
        self.Epoch.setObjectName("Epoch")
        self.TrainingMode = QtWidgets.QComboBox(self.centralwidget)
        self.TrainingMode.setGeometry(QtCore.QRect(310, 210, 69, 22))
        self.TrainingMode.setObjectName("TrainingMode")
        self.TrainingMode.addItem("")
        self.TrainingMode.addItem("")
        self.TrainingRatio = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.TrainingRatio.setGeometry(QtCore.QRect(310, 250, 62, 22))
        self.TrainingRatio.setObjectName("TrainingRatio")
        self.StartTrainingButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartTrainingButton.setGeometry(QtCore.QRect(340, 290, 101, 23))
        self.StartTrainingButton.setStyleSheet("QPushButton {\n"
                                               "color: #000;\n"
                                               "border: 2px solid #555;\n"
                                               "border-radius: 20px;\n"
                                               "border-style: outset;\n"
                                               "background: qradialgradient(\n"
                                               "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                               "radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
                                               ");\n"
                                               "padding: 1px;\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:hover {\n"
                                               "background: qradialgradient(\n"
                                               "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                               "radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
                                               ");\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:pressed {\n"
                                               "border-style: inset;\n"
                                               "background: qradialgradient(\n"
                                               "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                               "radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                               ");\n"
                                               "}")
        self.StartTrainingButton.setObjectName("StartTraininButton")
        self.Momentum = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Momentum.setGeometry(QtCore.QRect(490, 220, 62, 22))
        self.Momentum.setObjectName("Momentum")
        self.LearningRateText = QtWidgets.QLabel(self.centralwidget)
        self.LearningRateText.setGeometry(QtCore.QRect(410, 190, 71, 16))
        self.LearningRateText.setObjectName("LearningRateText")
        self.MomentumText = QtWidgets.QLabel(self.centralwidget)
        self.MomentumText.setGeometry(QtCore.QRect(420, 220, 61, 16))
        self.MomentumText.setObjectName("MomentumText")
        self.LearningRate = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.LearningRate.setGeometry(QtCore.QRect(490, 190, 62, 22))
        self.LearningRate.setObjectName("LearningRate")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(383, 170, 20, 111))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.AdvancedOptionsText = QtWidgets.QLabel(self.centralwidget)
        self.AdvancedOptionsText.setGeometry(QtCore.QRect(430, 170, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.AdvancedOptionsText.setFont(font)
        self.AdvancedOptionsText.setObjectName("AdvancedOptionsText")
        self.ImportDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.ImportDataButton.setGeometry(QtCore.QRect(210, 30, 91, 23))
        self.ImportDataButton.setStyleSheet("QPushButton {\n"
                                            "color: #000;\n"
                                            "border: 2px solid #555;\n"
                                            "border-radius: 20px;\n"
                                            "border-style: outset;\n"
                                            "background: qradialgradient(\n"
                                            "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                            "radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
                                            ");\n"
                                            "padding: 1px;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "background: qradialgradient(\n"
                                            "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                            "radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
                                            ");\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed {\n"
                                            "border-style: inset;\n"
                                            "background: qradialgradient(\n"
                                            "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                            "radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                            ");\n"
                                            "}")
        self.ImportDataButton.setObjectName("ImportDataButton")
        self.ImportImagesButton = QtWidgets.QPushButton(self.centralwidget)
        self.ImportImagesButton.setGeometry(QtCore.QRect(210, 60, 91, 23))
        self.ImportImagesButton.setStyleSheet("QPushButton {\n"
                                              "color: #000;\n"
                                              "border: 2px solid #555;\n"
                                              "border-radius: 20px;\n"
                                              "border-style: outset;\n"
                                              "background: qradialgradient(\n"
                                              "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                              "radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
                                              ");\n"
                                              "padding: 1px;\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:hover {\n"
                                              "background: qradialgradient(\n"
                                              "cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
                                              "radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
                                              ");\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:pressed {\n"
                                              "border-style: inset;\n"
                                              "background: qradialgradient(\n"
                                              "cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
                                              "radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
                                              ");\n"
                                              "}")
        self.ImportImagesButton.setObjectName("ImportImagesButton")
        self.ImportDataPath = QtWidgets.QLineEdit(self.centralwidget)
        self.ImportDataPath.setGeometry(QtCore.QRect(310, 30, 231, 20))
        self.ImportDataPath.setText("")
        self.ImportDataPath.setReadOnly(True)
        self.ImportDataPath.setObjectName("ImportDataPath")
        self.ImportImagesPath = QtWidgets.QLineEdit(self.centralwidget)
        self.ImportImagesPath.setGeometry(QtCore.QRect(310, 60, 231, 20))
        self.ImportImagesPath.setText("")
        self.ImportImagesPath.setReadOnly(True)
        self.ImportImagesPath.setObjectName("ImportImagesPath")
        self.previewImage = QtWidgets.QLabel(self.centralwidget)
        self.previewImage.setGeometry(QtCore.QRect(30, 30, 145, 108))
        self.previewImage.setStyleSheet("image: url(train_image.png);border :1px solid black;")
        self.previewImage.setText("")
        self.previewImage.setObjectName("previewImage")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 150, 180, 23))
        self.progressBar.setProperty("value", 99)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.ConfigureModelText = QtWidgets.QLabel(self.centralwidget)
        self.ConfigureModelText.setGeometry(QtCore.QRect(320, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ConfigureModelText.setFont(font)
        self.ConfigureModelText.setObjectName("ConfigureModelText")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Train Model"))
        self.EpochText.setText(_translate("MainWindow", "Epoch: "))
        self.TrainModeText.setText(_translate("MainWindow", "Training mode:"))
        self.TrainingRatioText.setText(_translate("MainWindow", "Training ratio: "))
        self.TrainingMode.setItemText(0, _translate("MainWindow", "CPU"))
        self.TrainingMode.setItemText(1, _translate("MainWindow", "GPU"))
        self.StartTrainingButton.setText(_translate("MainWindow", "Start training"))
        self.LearningRateText.setText(_translate("MainWindow", "Learning rate:"))
        self.MomentumText.setText(_translate("MainWindow", "Momentum:"))
        self.AdvancedOptionsText.setText(_translate("MainWindow", "Advanced Options"))
        self.ImportDataButton.setText(_translate("MainWindow", "Import Data"))
        self.ImportImagesButton.setText(_translate("MainWindow", "Import Images"))
        self.ConfigureModelText.setText(_translate("MainWindow", "Configure Model"))


class MyWindow(QtWidgets.QMainWindow, Ui_MainWindow):  # ++++
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.ImportDataButton.clicked.connect(self.ImportData)
        self.ImportImagesButton.clicked.connect(self.ImportImages)
        self.StartTrainingButton.clicked.connect(self.StartTraining)

    def ImportData(self):
        filename = QFileDialog.getOpenFileName(None, "Open Model",
                                               "", " Excel File *.xlsx")
        path = filename[0]
        self.ImportDataPath.setText(path)

    def ImportImages(self):
        filename = str(QFileDialog.getExistingDirectory(self, "Select Directory"))
        path = filename
        self.ImportImagesPath.setText(path)


    def StartTraining(self):

        self.worker = MainBackgroundThread(self.ImportDataPath.text(), self.ImportImagesPath.text(), self.Epoch.text(),self.TrainingMode.currentText(), self.TrainingRatio.text(), self.LearningRate.text(),self.Momentum.text(),self.previewImage)
        self.worker.start()





if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MyWindow()
    MainWindow.show()
    sys.exit(app.exec_())
